# Generated by Django 4.2.9 on 2024-05-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouh2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
