# Generated by Django 4.2.9 on 2024-05-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouh2', '0002_remove_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
