# Generated by Django 4.2.9 on 2024-05-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouh2', '0003_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='username',
        ),
    ]
